{{- if and .Values.sso.enabled (not .Values.sso.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swagger-admin.ssoSecretName" . }}
  labels:
     {{- include "swagger-admin.labels" . | nindent 4 }}
type: Opaque
data:
  OIDC_CLIENT_SECRET: {{ .Values.sso.clientSecret | b64enc | quote }}
  ENABLE_OIDC: {{ print "true" | b64enc | quote }}
  OIDC_METADATA_URL: {{ .Values.sso.metadataUrl | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.sso.clientID | b64enc | quote }}
  AUTH_CALLBACK: {{ .Values.sso.authCallback | b64enc | quote }}
{{- end }}