name: Building

on:
  workflow_call:
    outputs:
      version:
        description: version created on this build
        value: ${{ jobs.build.outputs.version }}

jobs:
  versioning:
    uses: ./.github/workflows/version.yaml
    with:
      runner: ubuntu-latest
  test:
    uses: ./.github/workflows/tests.yaml
  build:
    name: Building
    runs-on: ubuntu-latest
    needs: [versioning, test]
    outputs:
      version: ${{needs.versioning.outputs.FullSemVer}}
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ needs.versioning.outputs.FullSemVer }}
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
