name: Swagger workflow
on:
  release:
    types: [published]
  push:
    paths-ignore:
      - '.github/**'
      - './**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  standard_flow:
    name: Standard Flow
    uses: ./.github/workflows/build.yaml
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}