name: Swagger workflow
on:
  release:
    types: [published]
  push:
    paths-ignore:
      - '.github/**'
      - './**/*.md'
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  standard_flow:
    name: Standard Flow
    uses: ./.github/workflows/build.yaml
    secrets:
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}