name: Testing

on:
  workflow_call:

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
      - uses: astral-sh/ruff-action@v3
        name: Linting
      - name: Bandit
        uses: pyupio/bandit-action@v1
        with:
          args: --recursive --quiet --ignore-nosec
      - name: Pytest
        run: |
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt --with dev
          pip install -r requirements.txt
          pytest