name: Versioning

on:
  workflow_call:
    inputs:
      runner:
        description: "Runner Group Name"
        type: string
        required: false
        default: "ubuntu-latest"
    outputs:
      MajorMinorPatch:
        description: Major.Minor.Patch version
        value: ${{ jobs.version.outputs.MajorMinorPatch }}
      FullSemVer:
        description: Full semantic version
        value: ${{ jobs.version.outputs.FullSemVer }}

jobs:
  version:
    name: Find correct version
    runs-on: ${{ inputs.runner }}
    outputs:
      MajorMinorPatch: ${{ steps.output.outputs.MajorMinorPatch }}
      FullSemVer: ${{ steps.output.outputs.FullSemVer }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true
          configFilePath: .github/GitVersion.yaml
      - id: output
        if: github.event_name != 'release'
        run: |
          if [[ "${{ github.event_name }}" != "release" ]]; then
            echo "MajorMinorPatch=${{ env.GitVersion_MajorMinorPatch }}" >> "$GITHUB_OUTPUT"
            echo "FullSemVer=${{ env.GitVersion_FullSemVer }}" >> "$GITHUB_OUTPUT"
          else
            echo "MajorMinorPatch=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
            echo "FullSemVer=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
          fi
          echo '${{ toJson(github) }}' | jq .